<div class="preview-caldera-config-group">
	{{#unless hide_label}}<lable class="control-label">{{label}}{{#if required}} <span style="color:#ff0000;">*</span>{{/if}}</lable>{{/unless}}
	<div class="preview-caldera-config-field">
		<div style="background: #F5F5F5;" class="mce-container-body mce-flow-layout" id="previewmce_29-body">
			<div class="mce-container mce-flow-layout-item mce-first mce-last mce-btn-group" id="previewmce_30" role="group">
				<div id="previewmce_30-body">
				<div style="float:left;" aria-labelledby="previewmce_0" tabindex="-1" class="mce-widget mce-btn mce-first" id="previewmce_0" role="button" aria-label="Bold"><button tabindex="-1" type="button" role="presentation"><i class="mce-ico mce-i-bold"></i></button></div>
				<div style="float:left;" aria-labelledby="previewmce_1" tabindex="-1" class="mce-widget mce-btn" id="previewmce_1" role="button" aria-label="Italic"><button tabindex="-1" type="button" role="presentation"><i class="mce-ico mce-i-italic"></i></button></div>
				<div style="float:left;" aria-labelledby="previewmce_2" tabindex="-1" class="mce-widget mce-btn" id="previewmce_2" role="button" aria-label="Strikethrough"><button tabindex="-1" type="button" role="presentation"><i class="mce-ico mce-i-strikethrough"></i></button></div>
				<div style="float:left;" aria-labelledby="previewmce_3" tabindex="-1" class="mce-widget mce-btn" id="previewmce_3" role="button" aria-label="Bullet list"><button tabindex="-1" type="button" role="presentation"><i class="mce-ico mce-i-bullist"></i></button></div>
				<div style="float:left;" aria-labelledby="previewmce_4" tabindex="-1" class="mce-widget mce-btn" id="previewmce_4" role="button" aria-label="Numbered list"><button tabindex="-1" type="button" role="presentation"><i class="mce-ico mce-i-numlist"></i></button></div>
				<div style="float:left;" aria-labelledby="previewmce_5" tabindex="-1" class="mce-widget mce-btn" id="previewmce_5" role="button" aria-label="Blockquote"><button tabindex="-1" type="button" role="presentation"><i class="mce-ico mce-i-blockquote"></i></button></div>
				<div style="float:left;" aria-labelledby="previewmce_6" tabindex="-1" class="mce-widget mce-btn" id="previewmce_6" role="button" aria-label="Horizontal line"><button tabindex="-1" type="button" role="presentation"><i class="mce-ico mce-i-hr"></i></button></div>
				<div style="float:left;" aria-labelledby="previewmce_7" tabindex="-1" class="mce-widget mce-btn" id="previewmce_7" role="button" aria-label="Align left"><button tabindex="-1" type="button" role="presentation"><i class="mce-ico mce-i-alignleft"></i></button></div>
				<div style="float:left;" aria-labelledby="previewmce_8" tabindex="-1" class="mce-widget mce-btn" id="previewmce_8" role="button" aria-label="Align center"><button tabindex="-1" type="button" role="presentation"><i class="mce-ico mce-i-aligncenter"></i></button></div>
				<div style="float:left;" aria-labelledby="previewmce_9" tabindex="-1" class="mce-widget mce-btn" id="previewmce_9" role="button" aria-label="Align right"><button tabindex="-1" type="button" role="presentation"><i class="mce-ico mce-i-alignright"></i></button></div>
				<div style="float:left;" aria-labelledby="previewmce_10" tabindex="-1" class="mce-widget mce-btn" id="previewmce_10" role="button" aria-label="Insert/edit link"><button tabindex="-1" type="button" role="presentation"><i class="mce-ico mce-i-link"></i></button></div>
				<div style="float:left;" aria-labelledby="previewmce_11" tabindex="-1" class="mce-widget mce-btn" id="previewmce_11" role="button" aria-label="Remove link"><button tabindex="-1" type="button" role="presentation"><i class="mce-ico mce-i-unlink"></i></button></div>
				<div style="float:left;" aria-labelledby="previewmce_12" tabindex="-1" class="mce-widget mce-btn" id="previewmce_12" role="button" aria-label="Insert Read More tag"><button tabindex="-1" type="button" role="presentation"><i class="mce-ico mce-i-wp_more"></i></button></div>
				<div style="float:left;" aria-labelledby="previewmce_13" tabindex="-1" class="mce-widget mce-btn" id="previewmce_13" role="button" aria-label="Fullscreen"><button tabindex="-1" type="button" role="presentation"><i class="mce-ico mce-i-fullscreen"></i></button></div>
				<div style="float:left;" aria-labelledby="previewmce_14" tabindex="-1" class="mce-widget mce-btn mce-last" id="previewmce_14" role="button" aria-label="Toolbar Toggle"><button tabindex="-1" type="button" role="presentation"><i class="mce-ico mce-i-wp_adv"></i></button></div></div></div></div>
		<textarea {{#if hide_label}}placeholder="{{label}}"{{else}}placeholder="{{config/placeholder}}"{{/if}} rows="{{config/rows}}" style="resize:none; height:200px;" class="preview-field-config">{{config/default}}</textarea>
		<span class="help-block">{{caption}}</span>
	</div>
</div>